version: 2
jobs:
  build:
    working_directory: ~/wordfinder

    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout # check out source code to working directory

      - restore_cache:
          key: wordfinder-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline # gets the project dependencies

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: wordfinder-{{ checksum "pom.xml" }}

      - run: mvn package # run the actual tests

      - run: # uploads the test metadata from the `target/surefire-reports` directory so that it can show up in the CircleCI dashboard.
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - store_artifacts: #
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: target/wordfinder-1.0-SNAPSHOT.jar